name: face_attendance
description: On-device face recognition attendance app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  google_mlkit_face_detection: ^0.10.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  image: ^4.0.17
  vector_math: ^2.1.4
  csv: ^6.0.0
  permission_handler: ^11.0.1
  flutter_email_sender: ^6.0.2
  mailer: ^6.0.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet.tflite